module.exports = {
	server: 'https://ebey.aek56.com',
	author: 'https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx6261aaf547d02565&redirect_uri=https://ebey.aek56.com/api/zbzx/oauth/weixin/callback&response_type=code&scope=snsapi_userinfo&state=1',
	// server: 'http://dev.aek.com:8081',
	// author: '/',
	login: '/api/zbzx/oauth/auth4WechatOfficialAccounts',
	noticeList: '/api/cms/cmsContent/getNoticeListForMobile',
	newsList: '/api/cms/cmsContent/getNewsListForMobile',
	articleList: '/api/cms/cmsContent/getArticleListForMobile',
	complaintList: '/api/cms/cmsContent/getComplaintList',
	consultationList: '/api/cms/cmsContent/getConsultationList',
	detail: '/api/cms/cmsContent/getDetail?id=',
	detail2: '/api/cms/cmsContent/getBadAsk?id=',
	detail3: '/api/cms/cmsContent/getConsult?id=',
	replyList: '/api/cms/cmsReply/getBadAskReplyList?id=',
	replyList2: '/api/cms/cmsReply/getArticleReplyList?id=',
	stats: '/api/cms/cmsContent/stats',
	newBadAsk: '/api/cms/cmsContent/newBadAsk',
	newConsult: '/api/cms/cmsContent/newConsult',
	selectWxTenant: '/api/zbzxsys/tenant/selectWxTenant',
	newNotice: '/api/cms/cmsContent/newNotice',
	newNews: '/api/cms/cmsContent/newNews',
	newArticle: '/api/cms/cmsContent/newArticle',
	addArticleReply: '/api/cms/cmsReply/addArticleReply',
	addBadAskReply: '/api/cms/cmsReply/addBadAskReply',
	isNeedWeiXinBindingTips: '/api/zbzx/oauth/weixin/isNeedWeiXinBindingTips',
	disableWeiXinBinding: '/api/zbzx/oauth/weixin/disableWeiXinBinding',
	enableWeiXinBinding: '/api/zbzx/oauth/weixin/enableWeiXinBinding',
	deleteById: '/api/cms/cmsContent/deleteById?id=',
	getContentReturn: '/api/cms/cmsContent/getContentReturn?id=',
	editNotice: '/api/cms/cmsContent/editNotice',
	editNews: '/api/cms/cmsContent/editNews',
	editArticle: '/api/cms/cmsContent/editArticle',
	deleteBadConsultById: '/api/cms/cmsContent/deleteBadConsultById?id=',
	deletReply: '/api/cms/cmsReply/deletReply',
	upload: '/zuul/api/upload/zbzxfile',
	checkMobile: '/api2/zbzxsys/user/checkMobile?mobile=',
	sendCode: '/api2/zbzxsys/index/sendCode?account=',
	// resetPassword: '/api2/zbzxsys/index/resetPassword',
	resetPassword: '/api/zbzxsys/index/modifyPassword',
	getJsSdkConfigInfo: '/api/zbzx/oauth/weixin/getJsSdkConfigInfo?url=',
	uploadWeiXinImage: '/api/zbzx/oauth/weixin/uploadWeiXinImage',
	checkLoginName: '/api2/zbzxsys/user/checkLoginName?loginName='  // api2不需要token
};